import { Product } from "./product";

export const PRODUCTS:Product[]=[
    // {productId:1, productName:'Carrot', productImgUrl:'../assets/images/carrot.jpg', productPrice:220, productCatId:1 },
    // {productId:2, productName:'Potatoes', productImgUrl:'../assets/images/potatoes.jpg', productPrice:260, productCatId:1 },
    // {productId:3, productName:'Pumpkin', productImgUrl:'../assets/images/pumpkin.jpg', productPrice:150, productCatId:1 },
    // {productId:4, productName:'Cabbage', productImgUrl:'../assets/images/cabbage.jpg', productPrice:240, productCatId:1 },
    // {productId:5, productName:'Onions', productImgUrl:'../assets/images/onion.jpg', productPrice:140, productCatId:1 },
    // {productId:6, productName:'Banana', productImgUrl:'../assets/images/banana.jpg', productPrice:190, productCatId:2 },
    // {productId:7, productName:'Mango', productImgUrl:'../assets/images/mango.jpg', productPrice:210, productCatId:2 },
    // {productId:8 , productName:'Strawberries', productImgUrl:'../assets/images/strawberries.jpg', productPrice:600, productCatId:2 },
    // {productId:9, productName:'Oranges', productImgUrl:'../assets/images/orange.jpg' , productPrice:320, productCatId:2 },
    // {productId:10, productName:'Grapes', productImgUrl:'../assets/images/grapes.jpg', productPrice:400, productCatId:2 },
    // {productId:11, productName:'Sugar', productImgUrl:'../assets/images/sugar.jpg', productPrice:115, productCatId:3 },
    // {productId:12, productName:'Dhal', productImgUrl:'../assets/images/dhal.jpg', productPrice:219, productCatId:3 },
    // {productId:13, productName:'Samba', productImgUrl:'../assets/images/samba.jpeg', productPrice:190, productCatId:3 },
    // {productId:14, productName:'Cream Cracker', productImgUrl:'../assets/images/cream-crackers.jpg', productPrice:170, productCatId:3 },
    // {productId:15, productName:'Chilli Powder', productImgUrl:'../assets/images/chilli-powder.jpg', productPrice:93, productCatId:3 },
    // {productId:16, productName:'Tuna', productImgUrl:'../assets/images/tuna.jpg', productPrice:1420, productCatId:4 },
    // {productId:17, productName:'Shrimp', productImgUrl:'../assets/images/shrimp.jpg', productPrice:2440, productCatId:4 },
    // {productId:18, productName:'Cuttle Fish', productImgUrl:'../assets/images/cuttlefish.jpg', productPrice:2090, productCatId:4 },
    // {productId:19, productName:'Prawns', productImgUrl:'../assets/images/prawns.jpg', productPrice:990, productCatId:4 },
    // {productId:20, productName:'Thalapath', productImgUrl:'../assets/images/thalapath.jpg', productPrice:1990, productCatId:4 },
    // {productId:21, productName:'Chicken', productImgUrl:'../assets/images/chicken.jpg', productPrice:910, productCatId:5 },
    // {productId:22, productName:'Beef', productImgUrl:'../assets/images/beef.jpg', productPrice:2440, productCatId:5 },
    // {productId:23, productName:'Pork', productImgUrl:'../assets/images/pork.jpg', productPrice:2090, productCatId:5 },
    // {productId:24, productName:'Mutton', productImgUrl:'../assets/images/mutton.jpg', productPrice:990, productCatId:5 },
    // {productId:25, productName:'Sausages', productImgUrl:'../assets/images/sausages.jpg', productPrice:1990, productCatId:5 },
    // {productId:26, productName:'Cream Soda', productImgUrl:'../assets/images/cream-soda.jpg', productPrice:154, productCatId:6 },
    // {productId:27, productName:'Fesh Milk', productImgUrl:'../assets/images/freshmilk.jpg', productPrice:270, productCatId:6 },
    // {productId:28, productName:'Coca Cola', productImgUrl:'../assets/images/coca-cola.jpg', productPrice:220, productCatId:6 },
    // {productId:29, productName:'Milo', productImgUrl:'../assets/images/milo.jpg', productPrice:340, productCatId:6 },
    // {productId:30, productName:'Apple Jiuce' , productImgUrl:'../assets/images/apple-juice.jpg', productPrice:450, productCatId:6 },
    // {productId:31, productName:'Cheese', productImgUrl:'../assets/images/cheese.jpg', productPrice:620, productCatId:7 },
    // {productId:32, productName:'Yoghurt', productImgUrl:'../assets/images/yoghurt.jpg', productPrice:40, productCatId:7 },
    // {productId:33, productName:'Ice Cream', productImgUrl:'../assets/images/icecream.jpg', productPrice:680, productCatId:7 },
    // {productId:34, productName:'Butter', productImgUrl:'../assets/images/butter.jpg', productPrice:300, productCatId:7 },
    // {productId:35, productName:'Curd' , productImgUrl:'../assets/images/curd.jpg', productPrice:450, productCatId:7 },
]